### PR TITLE
major changes for better UX

### PR DESCRIPTION
**Pull request by AmmarHaddadi**
Hi , this is my **first** ever PR I really hope it gets accepted
* I made it possible to open and close the bar/tray/mini-bar with the **same** mouse button
* I made it display on top of the other because if it displays down it it pushes the windows under it which is annoying (bad UX)
* I also organized the config and explained most of stuff and what does it do for noobs
* I wrote a readme (sorry but the old one was just horrible)

I can say we did a pretty amazing job fixing a [5 years issue](https://github.com/polybar/polybar/issues/425) for non i3/bspwm users with nothing but polybar itself

### CODE REVIEW

**Comment by pietryszak** [comment]
It's shoud open on down, because it's extra bar if you use polybar. The idea was to open it like a tray bar. I use it's like this: main polybar with a small icon to open tiny polybar. The tiny_polyabr opens down with weather widget and network widget. Main polybar stays at up. @AmmarHaddadi 

But @phon31x shoud decide that we change a Tiny_bar. A solution to open and close is good idea, but i preffer to display tiny_bar
on down of other, like on video on readme. 

"I can say we did a pretty amazing job fixing a https://github.com/polybar/polybar/issues/425 for non i3/bspwm users with nothing but polybar itself"...great work @AmmarHaddadi @phon31x @pietryszak 

@AmmarHaddadi If you know python, mayby you are able to create some kind of option, one to open tiny_bar with current default approuch to open down of polybar, and second option just like this PR. Lest people choose ;)

**Comment by AmmarHaddadi** [comment]
### **Part1 : this PR wasn't actually wise**
@pietryszak actually I think that the original idea has an aesthetic purpose , while I shifted it to solve a problem that I faced , and if we merge those 2 ideas like you said we'll endup with a mess or a swiss army knife 
image

### Part 2 (u can ignore this) : how to merge the 2
 > maybe you are able to create some kind of option, one to ...

if anyone wants to do so , then you really need that python script , you will create 2 bars , and a py script for each so u can use 2 mouse buttons to do 4 things , but as I said , neither me or Phon31x would like to XD  

### Conclusion
so yeah I think I better leave this as @phon31x wants it , and leave my fork next to it , that's how GitHub works lol

**Comment by pietryszak** [comment]
> ### **Part1 : this PR wasn't actually wise**
> 
> @pietryszak actually I think that the original idea has an aesthetic purpose , while I shifted it to solve a problem that I faced , and if we merge those 2 ideas like you said we'll endup with a mess or a swiss army knife image
> ### Part 2 (u can ignore this) : how to merge the 2
> 
> > maybe you are able to create some kind of option, one to ...
> 
> if anyone wants to do so , then you really need that python script , you will create 2 bars , and a py script for each so u can use 2 mouse buttons to do 4 things , but as I said , neither me or Phon31x would like to XD
> ### Conclusion
> 
> so yeah I think I better leave this as @phon31x wants it , and leave my fork next to it , that's how GitHub works lol

Yes, I think this is the best solution. We stay in original way of working on this repo. Any you are free to change it with python script in yours forked version :)

**Comment by pietryszak** [comment]
We stay at original idea, @AmmarHaddadi maintain version python in it's own repo

**Pull request closed without merging**
